apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-flux-ite
  namespace: default
spec:
  interval: 1m
  targetNamespace: ite
  chart:
    spec:
      chart: test-flux
      version: "1.0.5"
      sourceRef:
        kind: HelmRepository
        name: test-flux-repo
        namespace: default
  values:
    service:
      nodePort: 30010