apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio
  namespace: default
spec:
  interval: 1m

  chart:
    spec:
      chart: portfolio
      version: "1.0.2"
      sourceRef:
        kind: HelmRepository
        name: portfolio-repo
        namespace: default
