apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portfolio-default
  namespace: default
spec:
  interval: 1m
  targetNamespace: default
  chart:
    spec:
      chart: portfolio
      version: "1.0.5"
      sourceRef:
        kind: HelmRepository
        name: portfolio-repo
        namespace: default
